# Generated by Django 5.0.1 on 2024-02-07 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yellowpage', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Business_Adderess',
            new_name='BusinessAdderess',
        ),
    ]
