# Generated by Django 5.0.1 on 2024-02-08 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yellowpage', '0003_businessadderess_logo_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessadderess',
            name='logo_url',
            field=models.FileField(blank=True, null=True, upload_to='business_logo/'),
        ),
    ]
