# Generated by Django 5.0.1 on 2024-02-08 07:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_number', models.CharField(max_length=50)),
                ('addressline1', models.CharField(max_length=128)),
                ('addressline2', models.CharField(max_length=128, null=True)),
                ('post_office', models.CharField(max_length=128)),
                ('city', models.CharField(max_length=128)),
                ('district', models.CharField(max_length=128)),
                ('state', models.CharField(max_length=128)),
                ('pin', models.CharField(max_length=6)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
